# Generated by Django 3.1.1 on 2020-09-08 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credentials', models.CharField(max_length=255)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reserved_operations', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_opened', models.BooleanField(default=True)),
            ],
        ),
    ]
